basePath: /
definitions:
  http.CreateNoteRequest:
    properties:
      plain_text:
        type: string
      title:
        type: string
    type: object
  http.ListNotesResponse:
    properties:
      notes:
        items:
          $ref: '#/definitions/models.NoteTransfer'
        type: array
    type: object
  http.UpdateNoteRequest:
    properties:
      id:
        type: string
      plain_text:
        type: string
      title:
        type: string
    type: object
  models.NoteTransfer:
    properties:
      id:
        type: string
      plain_text:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: yarik1448kuzmin@gmail.com
    name: Yaroslav Kuzmin
  description: Notes API
  title: Archipelago Notes API
  version: 1.0.1
paths:
  /notes:
    get:
      description: Get all notes
      produces:
      - application/json
      responses:
        "200":
          description: Notes
          schema:
            $ref: '#/definitions/http.ListNotesResponse'
        "400":
          description: Incorrect input
          schema: {}
        "500":
          description: Server error
          schema: {}
      summary: List notes
      tags:
      - Notes
    post:
      consumes:
      - application/json
      description: Create notes
      parameters:
      - description: Note info
        in: body
        name: noteInfo
        required: true
        schema:
          $ref: '#/definitions/http.CreateNoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Note created
          schema:
            $ref: '#/definitions/models.NoteTransfer'
        "400":
          description: Incorrect input
          schema: {}
        "500":
          description: Server error
          schema: {}
      summary: Create notes
      tags:
      - Notes
  /notes/{noteID}:
    delete:
      description: Delete notes by ID
      parameters:
      - description: Note ID
        in: path
        name: noteID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Note deleted
        "400":
          description: Incorrect input
          schema: {}
        "500":
          description: Server error
          schema: {}
      summary: Delete notes
      tags:
      - Notes
    get:
      description: Get note by ID
      parameters:
      - description: Note ID
        in: path
        name: noteID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Note
          schema:
            $ref: '#/definitions/models.NoteTransfer'
        "400":
          description: Incorrect input
          schema: {}
        "500":
          description: Server error
          schema: {}
      summary: Get note
      tags:
      - Notes
    post:
      consumes:
      - application/json
      description: Update note by ID
      parameters:
      - description: Note ID
        in: path
        name: noteID
        required: true
        type: integer
      - description: Note info
        in: body
        name: noteInfo
        required: true
        schema:
          $ref: '#/definitions/http.UpdateNoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated notes
          schema:
            $ref: '#/definitions/models.NoteTransfer'
        "400":
          description: Incorrect input
          schema: {}
        "500":
          description: Server error
          schema: {}
      summary: Update note
      tags:
      - Notes
schemes:
- https
- http
swagger: "2.0"
